ENT.Type = "ai"
ENT.Base = "base_ai"
ENT.Category = "TSS Objects"
ENT.PrintName = "TSS Guard"
ENT.Author = "N/A"
ENT.Purpose = "Patrol"
ENT.Instructions = "Patrol Maps"
ENT.Spawnable = true
ENT.AutoSpawnable = true
ENT.AdminSpawnable = false